### PR TITLE
Pass path to pulsar binary to avoid bin not found on control node

### LINKED ISSUE #16: Initialise ansible control node - JWT token generation cannot find pulsar bin
When executing 01.create_secFiles.yaml, the role [local_process/gen_secFile/create_jwt_token/](https://github.com/datastax/pulsar-ansible/blob/9ad586e/roles/local_process/gen_secFile/create_jwt_token/tasks/main.yaml) errors:

```
"Can't find \"pulsar\" executable which is necessary to create JWT tokens", "stdout_lines": ["Can't find \"pulsar\" executable which is necessary to create JWT tokens"
```

An environment variable should be passed to [genUserJwtToken.sh](https://github.com/datastax/pulsar-ansible/blob/736420f/bash/security/authentication/jwt/genUserJwtToken.sh), in order to use the pulsar binary installed on the ansible control node.

### PR DESCRIPTION
**Pull request by MMirelli**
Fixes #16 by injecting an environment variable based on the global value of `tgt_pulsar_inst_dir`.

### CODE REVIEW

**Comment by dave2wave** [comment]
Some considerations.

**Comment by dave2wave** [comment]
Some considerations:

**Comment by dave2wave** [comment]
Some considerations
1. The pulsar installation on the omb-runner is shared by all EVMT deployments.
2. The nbs4j framework is adjusted to use the pulsar-admin on client[0].

I think we need to discuss control node requirements for Pulsar-Ansible and EVMT.

**Comment by MMirelli** [comment]
> I think we need to discuss control node requirements for Pulsar-Ansible and EVMT.

I see your concern and I agree. IMO, it would be best to align the behaviour across the testing tools. So either we run pulsar binaries from the ansible control node or from a client, in this way we make sure we are using the same pulsar version and we reduce the complexity of the solution.  

> The pulsar installation on the omb-runner is shared by all EVMT deployments.

A nice feature would be to add a property in a global config file to select the pulsar version to use both on the server (VMs running pulsar) and client side (node where we are issuing `pulsar-admin` commands).

**Comment by MMirelli** [comment]
I would say this should be merged after https://github.com/datastax/pulsar-ansible/issues/24 is done.

**Review by yabinmeng — APPROVED** [review]
LGTM

**Pull request merged**
